language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.2
bundler_args: --without development
before_script:
  - while read line; do export $line; done < .env.test
  - createdb transferatu_test
  - bundle exec rake db:migrate
script: bundle exec rspec
notifications:
  email: false
addons:
  postgresql: "9.4"
